// Management strategy per segment — used to teach the user how to handle each group.
// All text in Thai. Used by Customer Segments page.

export interface SegmentStrategy {
  id: string
  level: 'marketing' | 'telesale' | 'ads'
  parent?: string
  label: string
  description: string
  color: string // tailwind bg
  ring: string // tailwind ring
  text: string // tailwind text
  emoji: string
  who: string
  goal: string
  actions: string[]
  channels: string[]
  offer: string
  kpi: string
  size: number // relative size weight 1-100
}

export const STRATEGIES: SegmentStrategy[] = [
  // === LEVEL 1: MARKETING (broadest, used for awareness + brand campaigns) ===
  {
    id: 'mk-vip-leaving',
    level: 'marketing',
    label: 'VIP กำลังจะหลุด',
    description: 'ลูกค้าชั้นเยี่ยมที่เริ่มห่าง 30-60 วัน',
    color: 'bg-rose-50',
    ring: 'ring-rose-200',
    text: 'text-rose-700',
    emoji: '👑',
    who: 'champion + recency 30-60d',
    goal: 'รักษาก่อนหลุดออกจาก VIP tier',
    actions: [
      'ส่งของขวัญพิเศษ / personal note จากเจ้าของแบรนด์',
      'Tier upgrade benefit',
      'LINE OA call แบบ 1:1',
    ],
    channels: ['LINE OA', 'SMS', 'Phone call'],
    offer: 'Free gift + exclusive bundle',
    kpi: 'ดึงกลับ ≥ 30% ภายใน 14 วัน',
    size: 90,
  },
  {
    id: 'mk-at-risk',
    level: 'marketing',
    label: 'ลูกค้าเสี่ยงหลุด',
    description: 'เริ่มซื้อน้อยลง 60-120 วัน',
    color: 'bg-amber-50',
    ring: 'ring-amber-200',
    text: 'text-amber-700',
    emoji: '⚠️',
    who: 'loyal + recency 60-120d',
    goal: 'กระตุ้นการซื้อซ้ำก่อนหายขาด',
    actions: [
      'Win-back coupon 15-20%',
      'Email + SMS reminder',
      'Retarget ads แบบเฉพาะเจาะจง',
    ],
    channels: ['Email', 'SMS', 'Facebook Ads'],
    offer: 'Coupon 200 บาท + ส่งฟรี',
    kpi: 'Conversion ≥ 15% ภายใน 30 วัน',
    size: 75,
  },
  {
    id: 'mk-rising-star',
    level: 'marketing',
    label: 'ดาวรุ่ง',
    description: 'ลูกค้าที่มีศักยภาพเป็น champion',
    color: 'bg-emerald-50',
    ring: 'ring-emerald-200',
    text: 'text-emerald-700',
    emoji: '🌟',
    who: 'potential + frequency 2-3x',
    goal: 'ผลักดันเป็น loyal/champion',
    actions: [
      'Bundle promotion + free gift',
      'แนะนำสินค้าระดับสูงขึ้น (upsell)',
      'ส่งเชิญเข้า VIP program',
    ],
    channels: ['LINE OA', 'Email', 'Web push'],
    offer: 'Upgrade bundle 12% off',
    kpi: 'Move to loyal ≥ 25% ใน 60 วัน',
    size: 65,
  },
  {
    id: 'mk-new-followup',
    level: 'marketing',
    label: 'ลูกค้าใหม่รอ Follow-up',
    description: 'ซื้อครั้งแรก 0-30 วัน ยังไม่กลับมา',
    color: 'bg-blue-50',
    ring: 'ring-blue-200',
    text: 'text-blue-700',
    emoji: '🌱',
    who: 'new + recency < 30d + frequency 1x',
    goal: 'Onboarding + กระตุ้นออเดอร์ที่ 2',
    actions: [
      'Welcome sequence (3 emails ใน 14 วัน)',
      'Coupon 150 บาท สำหรับออเดอร์ที่ 2',
      'รีวิวจริง + วิดีโอ how-to ใช้สินค้า',
    ],
    channels: ['Email', 'LINE OA', 'SMS'],
    offer: 'Coupon 150 บาท ใช้ได้ 7 วัน',
    kpi: 'Repeat rate ≥ 20% ใน 30 วัน',
    size: 50,
  },
  {
    id: 'mk-reactivate',
    level: 'marketing',
    label: 'Re-activation',
    description: 'ลูกค้าหลับ 120-180 วัน',
    color: 'bg-violet-50',
    ring: 'ring-violet-200',
    text: 'text-violet-700',
    emoji: '🔔',
    who: 'lost + recency 120-180d',
    goal: 'ดึงกลับมาด้วยข้อเสนอที่ใจป้ำที่สุด',
    actions: [
      'Flash sale 25-30% ส่ง LINE OA',
      'Best offer ที่เคยมี + limited time',
      'Personalized message อ้างถึงสินค้าที่เคยซื้อ',
    ],
    channels: ['LINE OA broadcast', 'SMS', 'FB retarget'],
    offer: 'Flash 30% + ส่งฟรี (48 ชม.)',
    kpi: 'Activation ≥ 8% ใน 14 วัน',
    size: 40,
  },

  // === LEVEL 2: TELESALE (subset — needs human contact) ===
  {
    id: 'ts-hot-warm',
    level: 'telesale',
    parent: 'mk-rising-star',
    label: 'Hot Lead — มีศักยภาพยังไม่ซื้อ',
    description: 'เพิ่ม Cart / ดู product 3+ ครั้ง',
    color: 'bg-orange-50',
    ring: 'ring-orange-200',
    text: 'text-orange-700',
    emoji: '🔥',
    who: 'view 3+ x · cart abandoned · ไม่ซื้อ 7 วัน',
    goal: 'โทรปิดการขายภายใน 48 ชม.',
    actions: [
      'Telesale โทรภายใน 24 ชม. หลัง cart abandon',
      'นำเสนอ bundle หรือ free gift',
      'Follow up ด้วย LINE OA หากไม่รับสาย',
    ],
    channels: ['Phone call', 'LINE OA', 'SMS'],
    offer: 'Coupon ส่วนบุคคล + ส่งฟรี',
    kpi: 'Close rate ≥ 25%',
    size: 60,
  },
  {
    id: 'ts-vip-care',
    level: 'telesale',
    parent: 'mk-vip-leaving',
    label: 'VIP Care — ขั้นเยี่ยมที่ยังอยู่กับเรา',
    description: 'VIP active · ต้องดูแลให้ทำ NPS สูง',
    color: 'bg-emerald-50',
    ring: 'ring-emerald-200',
    text: 'text-emerald-700',
    emoji: '💎',
    who: 'champion · active < 30d',
    goal: 'รักษาความสัมพันธ์ + ขอแนะนำเพื่อน',
    actions: [
      'Telesale โทรขอบคุณ + ขอ review',
      'ส่ง referral code ลด 200 ทั้งคู่',
      'เชิญเข้า VIP LINE group',
    ],
    channels: ['Phone call', 'LINE group'],
    offer: 'VIP referral 200x2',
    kpi: 'Referral ≥ 1 คน / VIP / เดือน',
    size: 55,
  },
  {
    id: 'ts-recover',
    level: 'telesale',
    parent: 'mk-at-risk',
    label: 'Recovery — ลูกค้าขั้นดีกำลังจะหายไป',
    description: 'หลุดจาก active 30-60 วัน',
    color: 'bg-amber-50',
    ring: 'ring-amber-200',
    text: 'text-amber-700',
    emoji: '⏳',
    who: 'loyal · recency 30-60d',
    goal: 'โทรดึงกลับด้วยข้อเสนอเฉพาะคน',
    actions: [
      'Telesale โทรถาม feedback + เสนอ bundle',
      'ส่ง coupon ส่วนตัวทาง LINE OA',
      'นัด Live demo / Q&A ถ้าจำเป็น',
    ],
    channels: ['Phone call', 'LINE OA'],
    offer: 'Personal coupon 15% off',
    kpi: 'Win-back ≥ 20%',
    size: 50,
  },
  {
    id: 'ts-newbie',
    level: 'telesale',
    parent: 'mk-new-followup',
    label: 'Newbie Onboarding',
    description: 'ลูกค้าใหม่ซื้อ 1 ครั้ง ยังไม่ใช้สินค้า',
    color: 'bg-blue-50',
    ring: 'ring-blue-200',
    text: 'text-blue-700',
    emoji: '👋',
    who: 'new · ซื้อ 1x · ยังไม่มี review',
    goal: 'สอนใช้สินค้า + กระตุ้นออเดอร์ 2',
    actions: [
      'Telesale โทรหลัง 7 วัน ถามผลใช้',
      'แนะนำวิธีใช้ที่ถูกต้อง',
      'เสนอสินค้าเสริมพร้อมส่วนลด',
    ],
    channels: ['Phone call', 'LINE OA'],
    offer: 'Cross-sell discount 10%',
    kpi: 'Order 2 rate ≥ 25%',
    size: 45,
  },

  // === LEVEL 3: ADS (narrowest — used for paid acquisition + retargeting) ===
  {
    id: 'ads-lookalike',
    level: 'ads',
    parent: 'ts-vip-care',
    label: 'Lookalike VIP',
    description: 'หาคนใหม่ที่คล้าย VIP ใน FB/TikTok',
    color: 'bg-purple-50',
    ring: 'ring-purple-200',
    text: 'text-purple-700',
    emoji: '🎯',
    who: 'FB Lookalike 1% from champion list',
    goal: 'Acquisition คุณภาพสูง',
    actions: [
      'Upload VIP list to FB Ads',
      'สร้าง Lookalike 1-3% audience',
      'รัน ads แบบ direct response',
    ],
    channels: ['Facebook Ads', 'TikTok Ads'],
    offer: 'First-time 20% off + ส่งฟรี',
    kpi: 'CPA < 300 บาท',
    size: 40,
  },
  {
    id: 'ads-retarget-cart',
    level: 'ads',
    parent: 'ts-hot-warm',
    label: 'Retarget Cart Abandon',
    description: 'คนที่เพิ่ม cart แล้วไม่จ่าย 7 วัน',
    color: 'bg-orange-50',
    ring: 'ring-orange-200',
    text: 'text-orange-700',
    emoji: '🛒',
    who: 'visited /cart · no purchase 7d',
    goal: 'ดึงกลับมาจ่ายเงิน',
    actions: [
      'Dynamic Product Ads (DPA)',
      'แสดงสินค้าที่ใส่ไว้ + reminder',
      'Limited stock / time pressure',
    ],
    channels: ['Facebook Ads', 'Google DPA'],
    offer: 'Coupon 100 บาท',
    kpi: 'ROAS ≥ 3.0',
    size: 35,
  },
  {
    id: 'ads-retarget-view',
    level: 'ads',
    parent: 'ts-hot-warm',
    label: 'Retarget Viewed Product',
    description: 'ดูสินค้า 3+ ครั้งใน 14 วัน',
    color: 'bg-cyan-50',
    ring: 'ring-cyan-200',
    text: 'text-cyan-700',
    emoji: '👀',
    who: 'product view × 3 in 14d',
    goal: 'Educate + ดึงเข้า cart',
    actions: [
      'Video testimonial ads',
      'Social proof ads (review)',
      'Comparison content',
    ],
    channels: ['Facebook Reels', 'TikTok'],
    offer: 'Free trial pack',
    kpi: 'CTR ≥ 2%',
    size: 30,
  },
  {
    id: 'ads-reengage-90',
    level: 'ads',
    parent: 'mk-reactivate',
    label: 'Re-engage 90d',
    description: 'ไม่กลับเข้าเว็บ 90 วัน',
    color: 'bg-rose-50',
    ring: 'ring-rose-200',
    text: 'text-rose-700',
    emoji: '💔',
    who: 'inactive 90+ days',
    goal: 'Win-back ด้วย flash deal',
    actions: [
      'Best-ever offer (≥ 30% off)',
      'Personalized reminder ads',
      'Email + SMS combined',
    ],
    channels: ['Facebook Ads', 'Email', 'SMS'],
    offer: 'Best deal 30% + free shipping',
    kpi: 'Activation ≥ 5%',
    size: 25,
  },
]

export const getStrategies = (level: 'marketing' | 'telesale' | 'ads') =>
  STRATEGIES.filter((s) => s.level === level)

export const getChildren = (parentId: string) =>
  STRATEGIES.filter((s) => s.parent === parentId)
